name: Laravel CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, mysql, sqlite, curl, xml, ctype, json, bcmath, pcntl, pdo, tokenizer

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Generate .env file
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run migrations and seeders
        run: |
          php artisan migrate --seed

      - name: Run tests
        run: |
          vendor/bin/phpunit
